### ISSUE TITLE
At initial start or refresh dashboard not scrollable

### ISSUE THREAD

**Issue by GRyabkin** [Mehmetyaz/dashboard#8]
When I run sample from the repository I am seeing that dashboard isn't scrollable until I make an edit or call refresh state using debugger. Any suggestions how it can be fixed?

[✓] Flutter (Channel stable, 3.0.5, on macOS 13.1 22C65 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at */flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Android 32/33

**Comment by GRyabkin** [comment]
I found this fork with a fix https://github.com/Mehmetyaz/dashboard/commit/5be5314d362272b6c0995c76e9e5a7737e6e5219

I tried today investigate why with the fix there's no scrolling issue at initialising.

1. `setCanDrag` not called during `viewportBuilder` offset change. It should be called at `applyViewportDimension` and for the dashboard ViewportOffset is instance of _SingleChildViewport 
2. `setCanDrag` replaced gesture recognizers which are empty initially only when currentState not null which is not null only after a first build

Therefore the fix works because it prefill `gestureRecognizers` before first build is invoked

I am not sure does it make sense or not but this is what I have found so far.

**Comment by Mehmetyaz** [comment]
I did not experience this problem. Despite all my attempts it works correctly every time. I think there is an edge case and you should explain it better.

We set the viewport dimensions with the `_setNewOffset` method in `_DashboardState` and if necessary, `Scrollable` performs the `setCanDrag` operation.

I can't always set it to true because in some cases it might not be scrollable. That's exactly why `setCanDrag` is protected.

While testing, you can find out if anything went wrong by doing a print in `_setNewOffset` before calling `offset.applyViewportDimension`.

**Comment by Mehmetyaz** [comment]
See version 0.0.3+1

**Comment by GRyabkin** [comment]
Yes it works for me, refresh on postcallback solved the issue
